const List<String> complimentsEn = [
  "You look absolutely stunning today.",
  "That smile just made my day brighter.",
  "Your eyes are incredibly beautiful.",
  "You're glowing with confidence.",
  "Your style is on point today.",
  "You have such a warm, friendly face.",
  "Looking good! You're killing it.",
  "Your hair looks fantastic right now.",
  "You bring positive energy into the room.",
  "That outfit really suits you perfectly.",
  "You have a naturally beautiful smile.",
  "You look fresh and full of life.",
  "You're rocking that look today.",
  "Such a charming and kind face.",
  "You look confident and handsome.",
  "Your vibe is genuinely attractive.",
  "You have such nice features.",
  "Looking sharp and put together.",
  "Your reflection looks absolutely radiant today.",
  "You're glowing in that mirror.",
  "That smile in the reflection is beautiful.",
  "Your eyes shine so brightly right now.",
  "Looking at your reflection, you seem confident and strong.",
  "Your style looks perfect in the mirror.",
  "You have such a warm and kind reflection.",
  "The mirror loves showing you off today.",
  "Your hair looks amazing in this light.",
  "You bring such positive energy to your reflection.",
  "That outfit suits your reflection perfectly.",
  "Your reflection shows how great you're feeling.",
  "You look fresh and full of life in the mirror.",
  "Such a charming reflection staring back at you.",
  "Your reflection is rocking that look.",
  "You appear naturally beautiful right now.",
  "The mirror is highlighting your best features.",
  "You look sharp and put together in your reflection.",
  "Your reflection radiates confidence and charm.",
  "Looking in the mirror, you're truly stunning.",
];

const List<String> complimentsDe = [
  "Du siehst heute absolut umwerfend aus.",
  "Dieses Lächeln hat meinen Tag erhellt.",
  "Deine Augen sind unglaublich schön.",
  "Du strahlst vor Selbstbewusstsein.",
  "Dein Stil ist heute genau richtig.",
  "Du hast so ein warmes, freundliches Gesicht.",
  "Gut siehst du aus! Du rockst das heute.",
  "Deine Haare sehen gerade fantastisch aus.",
  "Du bringst so eine positive Energie in den Raum.",
  "Dieses Outfit steht dir einfach perfekt.",
  "Du hast ein von Natur aus wunderschönes Lächeln.",
  "Du siehst frisch und voller Leben aus.",
  "Du rockst diesen Look heute.",
  "So ein charmantes und freundliches Gesicht.",
  "Du siehst selbstbewusst und gutaussehend aus.",
  "Deine Ausstrahlung ist wirklich attraktiv.",
  "Du hast so schöne Gesichtszüge.",
  "Scharf und gepflegt siehst du aus.",
  "Dein Spiegelbild sieht heute absolut strahlend aus.",
  "Du glühst förmlich im Spiegel.",
  "Das Lächeln im Spiegel ist wunderschön.",
  "Deine Augen leuchten gerade so hell.",
  "Im Spiegel wirkst du selbstbewusst und stark.",
  "Dein Stil sieht im Spiegel perfekt aus.",
  "Du hast so ein warmes und freundliches Spiegelbild.",
  "Der Spiegel zeigt dich heute von deiner besten Seite.",
  "Deine Haare sehen in diesem Licht fantastisch aus.",
  "Du bringst so eine positive Energie in dein Spiegelbild.",
  "Dieses Outfit passt perfekt zu deinem Spiegelbild.",
  "Dein Spiegelbild zeigt, wie großartig du dich fühlst.",
  "Du siehst frisch und voller Leben im Spiegel aus.",
  "Was für ein charmantes Spiegelbild schaut dich an.",
  "Dein Spiegelbild rockt diesen Look.",
  "Du wirkst gerade von Natur aus wunderschön.",
  "Der Spiegel betont deine schönsten Seiten.",
  "Du siehst scharf und gepflegt in deinem Spiegelbild aus.",
  "Dein Spiegelbild strahlt Selbstbewusstsein und Charme aus.",
  "Im Spiegel bist du wirklich umwerfend.",
];
