const List<String> insultsEn = [
  "You look like a visible fart.",
  "Maybe if you eat all that makeup you'll be beautiful on the inside.",
  "You're so stupid, you failed a blood test.",
  "People like you are the reason shampoo bottles have instructions.",
  "I envy people who haven't met you.",
  "You smell like goat cheese.",
  "Go away, I was looking at something better than you.",
  "If beauty is skin deep, you must be transparent.",
  "I bet your old mirror has filed for divorce three times already.",
  "You look like the 'before' picture that never found the 'after'.",
  "Your face is proof that God has a sense of humor and zero mercy.",
  "Even autocorrect gave up trying to fix your face.",
  "You're the reason warning labels exist on mirrors.",
  "Your beauty is so rare… it's basically extinct.",
  "You're what happens when evolution hits the snooze button.",
  "Your reflection just filed a restraining order.",
  "Even Photoshop said 'nah, this one's beyond saving'.",
  "You're so ugly, every camera is actively trying to blur you out.",
  "The only thing symmetrical about you is how equally bad both sides look.",
  "Your confidence is impressive for someone who looks like a rejected Pixar character.",
  "You're the human equivalent of Comic Sans — nobody asked for this.",
  "Your face is what happens when the universe runs out of good ideas.",
  "Your face looks like it lost a fight with a cheese grater.",
  "Even your shadow tries to sneak away when you walk by.",
  "You look like something the cat dragged in and then immediately regretted.",
  "You look like a before picture that got stuck in permanent before.",
  "Your face is why some animals eat their young.",
  "You're so ugly your mom probably still has the receipt.",
  "Your confidence is cute for someone who looks like a rejected Halloween mask.",
  "You're what happens when the universe runs out of fucks to give about symmetry.",
  "Your parents must have been aiming for a participation trophy in genetics.",
  "You look like a human version of a software update that nobody wanted.",
  "Your beauty is so deep it hasn't been discovered yet.",
];

const List<String> insultsDe = [
  "Du siehst aus wie ein sichtbarer Furz.",
  "Vielleicht bist du innen schön, wenn du das ganze Make-up aufisst.",
  "Du bist so dumm, du hast einen Bluttest nicht bestanden.",
  "Leute wie du sind der Grund, warum Shampooflaschen Gebrauchsanweisungen haben.",
  "Ich beneide die Menschen, die dich noch nicht kennen.",
  "Du riechst nach Ziegenkäse.",
  "Geh weg, ich habe mir gerade etwas Schöneres angeschaut.",
  "Wenn Schönheit nur unter der Haut liegt, musst du wohl durchsichtig sein.",
  "Ich wette, dein alter Spiegel hat schon dreimal die Scheidung eingereicht.",
  "Du siehst aus wie das 'Vorher'-Bild, das nie ein 'Nachher' gefunden hat.",
  "Dein Gesicht beweist, dass Gott Humor hat — und null Mitleid.",
  "Selbst die Autokorrektur hat aufgehört, dein Gesicht zu korrigieren.",
  "Du bist der Grund, warum Spiegel Warnhinweise brauchen.",
  "Deine Schönheit ist so selten… sie ist praktisch ausgestorben.",
  "Du bist das Ergebnis, wenn die Evolution auf Snooze drückt.",
  "Dein Spiegelbild hat gerade eine einstweilige Verfügung beantragt.",
  "Selbst Photoshop hat gesagt: 'Nein, das ist hoffnungslos'.",
  "Du bist so hässlich, dass jede Kamera aktiv versucht, dich unscharf zu stellen.",
  "Das Einzige Symmetrische an dir ist, wie gleich schlecht beide Seiten aussehen.",
  "Dein Selbstbewusstsein ist beeindruckend für jemanden, der aussieht wie eine abgelehnte Pixar-Figur.",
  "Du bist das menschliche Äquivalent von Comic Sans — niemand hat darum gebeten.",
  "Dein Gesicht ist das, was passiert, wenn dem Universum die guten Ideen ausgehen.",
  "Dein Gesicht sieht aus, als hätte es einen Kampf mit einer Käsereibe verloren.",
  "Selbst dein Schatten versucht wegzuschleichen, wenn du vorbeigehst.",
  "Du siehst aus wie etwas, das die Katze reingeschleppt hat und sofort bereut hat.",
  "Du siehst aus wie ein Vorher-Bild, das permanent im Vorher feststeckt.",
  "Dein Gesicht ist der Grund, warum manche Tiere ihren Nachwuchs fressen.",
  "Du bist so hässlich, deine Mutter hat wahrscheinlich noch den Kassenbon.",
  "Dein Selbstbewusstsein ist süß für jemanden, der aussieht wie eine abgelehnte Halloween-Maske.",
  "Du bist das Ergebnis, wenn dem Universum die Energie für Symmetrie ausgeht.",
  "Deine Eltern müssen auf eine Teilnahmetrophäe in der Genetik gezielt haben.",
  "Du siehst aus wie die menschliche Version eines Softwareupdates, das niemand wollte.",
  "Deine Schönheit ist so tief, sie wurde noch nicht entdeckt.",
];
