const List<String> insults18En = [
  "Of all the semen pumped into your mother, how the fuck did you win out?",
  "Out of 100,000 sperm, you were the fastest?",
  "Of all the loads your mom swallowed, you were the only one that stuck?",
  "Your dad must’ve nutted in a trash bag and somehow you crawled out.",
  "Congratulations, you’re the cumshot that should’ve hit the sheets instead.",
  "Your mother’s pussy must’ve been a participation trophy that night.",
  "You’re what happens when the condom breaks and God laughs.",
  "Your dad’s sperm took one look at the egg and still said “fuck it.”",
  "You’re proof that even the worst swimmers sometimes cross the finish line.",
  "Your mom should’ve swallowed harder that night.",
  "Out of billions of sperm, you were the genetic participation award.",
  "You’re the reason your dad pulls out now.",
  "Your mother’s womb must’ve been running a charity for defective loads.",
  "You were the sperm that lost the race but still got the medal.",
  "Of all the nut your mom took, you were clearly the leftover drip.",
  "You’re what happens when sperm cells have no standards.",
  "Your mom swallowed 99 good loads and then you happened.",
  "Congratulations, you’re the cum that should’ve been wiped off the belly.",
  "Your parents’ best swimmers clearly took a wrong turn that night.",
];

const List<String> insults18De = [
  "Von all dem Sperma, das in deine Mutter gepumpt wurde – wie zur Hölle hast du gewonnen?",
  "Von 100.000 Spermien warst du das schnellste?",
  "Von all den Ladungen, die deine Mutter geschluckt hat, bist du der Einzige, der hängen geblieben ist?",
  "Dein Vater muss in einen Müllsack abgespritzt haben, und irgendwie bist du rausgekrochen.",
  "Glückwunsch, du bist der Abschuss, der eigentlich auf dem Laken landen sollte.",
  "Die Muschi deiner Mutter muss an dem Abend einen Teilnahme-Pokal vergeben haben.",
  "Du bist das, was passiert, wenn das Kondom reißt und Gott lacht.",
  "Die Spermien deines Vaters haben das Ei gesehen und trotzdem gesagt: „Ach, scheiß drauf.“",
  "Du bist der Beweis, dass sogar die schlechtesten Schwimmer manchmal ins Ziel kommen.",
  "Deine Mutter hätte in dieser Nacht stärker schlucken sollen.",
  "Von Milliarden Spermien warst du der genetische Trostpreis.",
  "Du bist der Grund, warum dein Vater jetzt immer rauszieht.",
  "Der Schoß deiner Mutter muss an dem Abend eine Wohltätigkeitsveranstaltung für defekte Ladungen veranstaltet haben.",
  "Du warst das Spermium, das das Rennen verloren hat, aber trotzdem die Medaille bekommen hat.",
  "Von all dem Sperma, das deine Mutter genommen hat, warst du eindeutig der übriggebliebene Tropfen.",
  "Du bist das, was passiert, wenn Spermien keinerlei Ansprüche haben.",
  "Deine Mutter hat 99 gute Ladungen geschluckt und dann bist du passiert.",
  "Glückwunsch, du bist das Sperma, das eigentlich vom Bauch hätte weggewischt werden sollen.",
  "Die besten Schwimmer deiner Eltern haben in dieser Nacht eindeutig die falsche Abzweigung genommen.",
];
