// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library back_front;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;


import './dashboard_dashboard_structure_generated.dart' as dashboard_structure;
import './view_view_structure_generated.dart' as view_structure;

enum SimpleCommandType {
  STANDBY(0),
  WAKEUP(1),
  QUIT(2),
  NEXT_THEME(3),
  UP(4),
  DOWN(5),
  LEFT(6),
  RIGHT(7),
  PUSH(8),
  PULL(9),
  CLOCKWISE_ROTATION(10),
  ANTICLOCKWISE_ROTATION(11),
  WAVE(12);

  final int value;
  const SimpleCommandType(this.value);

  factory SimpleCommandType.fromValue(int value) {
    switch (value) {
      case 0: return SimpleCommandType.STANDBY;
      case 1: return SimpleCommandType.WAKEUP;
      case 2: return SimpleCommandType.QUIT;
      case 3: return SimpleCommandType.NEXT_THEME;
      case 4: return SimpleCommandType.UP;
      case 5: return SimpleCommandType.DOWN;
      case 6: return SimpleCommandType.LEFT;
      case 7: return SimpleCommandType.RIGHT;
      case 8: return SimpleCommandType.PUSH;
      case 9: return SimpleCommandType.PULL;
      case 10: return SimpleCommandType.CLOCKWISE_ROTATION;
      case 11: return SimpleCommandType.ANTICLOCKWISE_ROTATION;
      case 12: return SimpleCommandType.WAVE;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static SimpleCommandType? _createOrNull(int? value) =>
      value == null ? null : SimpleCommandType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 12;
  static const fb.Reader<SimpleCommandType> reader = _SimpleCommandTypeReader();
}

class _SimpleCommandTypeReader extends fb.Reader<SimpleCommandType> {
  const _SimpleCommandTypeReader();

  @override
  int get size => 1;

  @override
  SimpleCommandType read(fb.BufferContext bc, int offset) =>
      SimpleCommandType.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum InfoType {
  CAN_UPDATE(0),
  MUST_UPDATE(1),
  FACE_TRAINING(2);

  final int value;
  const InfoType(this.value);

  factory InfoType.fromValue(int value) {
    switch (value) {
      case 0: return InfoType.CAN_UPDATE;
      case 1: return InfoType.MUST_UPDATE;
      case 2: return InfoType.FACE_TRAINING;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static InfoType? _createOrNull(int? value) =>
      value == null ? null : InfoType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static const fb.Reader<InfoType> reader = _InfoTypeReader();
}

class _InfoTypeReader extends fb.Reader<InfoType> {
  const _InfoTypeReader();

  @override
  int get size => 1;

  @override
  InfoType read(fb.BufferContext bc, int offset) =>
      InfoType.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum BackFrontPayloadTypeId {
  NONE(0),
  SimpleCommand(1),
  viewStructure_View(2),
  GetToken(3),
  dashboardStructure_Dashboard(4),
  WakeUpMessage(5),
  DisplayInfo(6),
  SystemInfo(7);

  final int value;
  const BackFrontPayloadTypeId(this.value);

  factory BackFrontPayloadTypeId.fromValue(int value) {
    switch (value) {
      case 0: return BackFrontPayloadTypeId.NONE;
      case 1: return BackFrontPayloadTypeId.SimpleCommand;
      case 2: return BackFrontPayloadTypeId.viewStructure_View;
      case 3: return BackFrontPayloadTypeId.GetToken;
      case 4: return BackFrontPayloadTypeId.dashboardStructure_Dashboard;
      case 5: return BackFrontPayloadTypeId.WakeUpMessage;
      case 6: return BackFrontPayloadTypeId.DisplayInfo;
      case 7: return BackFrontPayloadTypeId.SystemInfo;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static BackFrontPayloadTypeId? _createOrNull(int? value) =>
      value == null ? null : BackFrontPayloadTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 7;
  static const fb.Reader<BackFrontPayloadTypeId> reader = _BackFrontPayloadTypeIdReader();
}

class _BackFrontPayloadTypeIdReader extends fb.Reader<BackFrontPayloadTypeId> {
  const _BackFrontPayloadTypeIdReader();

  @override
  int get size => 1;

  @override
  BackFrontPayloadTypeId read(fb.BufferContext bc, int offset) =>
      BackFrontPayloadTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class SimpleCommand {
  SimpleCommand._(this._bc, this._bcOffset);
  factory SimpleCommand(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<SimpleCommand> reader = _SimpleCommandReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  SimpleCommandType get type => SimpleCommandType.fromValue(const fb.Int8Reader().vTableGet(_bc, _bcOffset, 4, 0));

  @override
  String toString() {
    return 'SimpleCommand{type: ${type}}';
  }
}

class _SimpleCommandReader extends fb.TableReader<SimpleCommand> {
  const _SimpleCommandReader();

  @override
  SimpleCommand createObject(fb.BufferContext bc, int offset) => 
    SimpleCommand._(bc, offset);
}

class SimpleCommandBuilder {
  SimpleCommandBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addType(SimpleCommandType? type) {
    fbBuilder.addInt8(0, type?.value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class SimpleCommandObjectBuilder extends fb.ObjectBuilder {
  final SimpleCommandType? _type;

  SimpleCommandObjectBuilder({
    SimpleCommandType? type,
  })
      : _type = type;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addInt8(0, _type?.value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class GetToken {
  GetToken._(this._bc, this._bcOffset);
  factory GetToken(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<GetToken> reader = _GetTokenReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get provider => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get accessToken => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get tokenType => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  String? get url => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);

  @override
  String toString() {
    return 'GetToken{provider: ${provider}, accessToken: ${accessToken}, tokenType: ${tokenType}, url: ${url}}';
  }
}

class _GetTokenReader extends fb.TableReader<GetToken> {
  const _GetTokenReader();

  @override
  GetToken createObject(fb.BufferContext bc, int offset) => 
    GetToken._(bc, offset);
}

class GetTokenBuilder {
  GetTokenBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addProviderOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addAccessTokenOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addTokenTypeOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addUrlOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class GetTokenObjectBuilder extends fb.ObjectBuilder {
  final String? _provider;
  final String? _accessToken;
  final String? _tokenType;
  final String? _url;

  GetTokenObjectBuilder({
    String? provider,
    String? accessToken,
    String? tokenType,
    String? url,
  })
      : _provider = provider,
        _accessToken = accessToken,
        _tokenType = tokenType,
        _url = url;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? providerOffset = _provider == null ? null
        : fbBuilder.writeString(_provider!);
    final int? accessTokenOffset = _accessToken == null ? null
        : fbBuilder.writeString(_accessToken!);
    final int? tokenTypeOffset = _tokenType == null ? null
        : fbBuilder.writeString(_tokenType!);
    final int? urlOffset = _url == null ? null
        : fbBuilder.writeString(_url!);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, providerOffset);
    fbBuilder.addOffset(1, accessTokenOffset);
    fbBuilder.addOffset(2, tokenTypeOffset);
    fbBuilder.addOffset(3, urlOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class WakeUpMessage {
  WakeUpMessage._(this._bc, this._bcOffset);
  factory WakeUpMessage(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<WakeUpMessage> reader = _WakeUpMessageReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get language => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get userName => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'WakeUpMessage{language: ${language}, userName: ${userName}}';
  }
}

class _WakeUpMessageReader extends fb.TableReader<WakeUpMessage> {
  const _WakeUpMessageReader();

  @override
  WakeUpMessage createObject(fb.BufferContext bc, int offset) => 
    WakeUpMessage._(bc, offset);
}

class WakeUpMessageBuilder {
  WakeUpMessageBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addLanguageOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addUserNameOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class WakeUpMessageObjectBuilder extends fb.ObjectBuilder {
  final String? _language;
  final String? _userName;

  WakeUpMessageObjectBuilder({
    String? language,
    String? userName,
  })
      : _language = language,
        _userName = userName;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? languageOffset = _language == null ? null
        : fbBuilder.writeString(_language!);
    final int? userNameOffset = _userName == null ? null
        : fbBuilder.writeString(_userName!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, languageOffset);
    fbBuilder.addOffset(1, userNameOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class DisplayInfo {
  DisplayInfo._(this._bc, this._bcOffset);
  factory DisplayInfo(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DisplayInfo> reader = _DisplayInfoReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get language => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  InfoType get type => InfoType.fromValue(const fb.Int8Reader().vTableGet(_bc, _bcOffset, 6, 0));

  @override
  String toString() {
    return 'DisplayInfo{language: ${language}, type: ${type}}';
  }
}

class _DisplayInfoReader extends fb.TableReader<DisplayInfo> {
  const _DisplayInfoReader();

  @override
  DisplayInfo createObject(fb.BufferContext bc, int offset) => 
    DisplayInfo._(bc, offset);
}

class DisplayInfoBuilder {
  DisplayInfoBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addLanguageOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addType(InfoType? type) {
    fbBuilder.addInt8(1, type?.value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DisplayInfoObjectBuilder extends fb.ObjectBuilder {
  final String? _language;
  final InfoType? _type;

  DisplayInfoObjectBuilder({
    String? language,
    InfoType? type,
  })
      : _language = language,
        _type = type;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? languageOffset = _language == null ? null
        : fbBuilder.writeString(_language!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, languageOffset);
    fbBuilder.addInt8(1, _type?.value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class SystemInfo {
  SystemInfo._(this._bc, this._bcOffset);
  factory SystemInfo(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<SystemInfo> reader = _SystemInfoReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get cpu => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 4, 0.0);
  double get ram => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 6, 0.0);
  double get storage => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 8, 0.0);

  @override
  String toString() {
    return 'SystemInfo{cpu: ${cpu}, ram: ${ram}, storage: ${storage}}';
  }
}

class _SystemInfoReader extends fb.TableReader<SystemInfo> {
  const _SystemInfoReader();

  @override
  SystemInfo createObject(fb.BufferContext bc, int offset) => 
    SystemInfo._(bc, offset);
}

class SystemInfoBuilder {
  SystemInfoBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addCpu(double? cpu) {
    fbBuilder.addFloat32(0, cpu);
    return fbBuilder.offset;
  }
  int addRam(double? ram) {
    fbBuilder.addFloat32(1, ram);
    return fbBuilder.offset;
  }
  int addStorage(double? storage) {
    fbBuilder.addFloat32(2, storage);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class SystemInfoObjectBuilder extends fb.ObjectBuilder {
  final double? _cpu;
  final double? _ram;
  final double? _storage;

  SystemInfoObjectBuilder({
    double? cpu,
    double? ram,
    double? storage,
  })
      : _cpu = cpu,
        _ram = ram,
        _storage = storage;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(3);
    fbBuilder.addFloat32(0, _cpu);
    fbBuilder.addFloat32(1, _ram);
    fbBuilder.addFloat32(2, _storage);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BackFrontMessage {
  BackFrontMessage._(this._bc, this._bcOffset);
  factory BackFrontMessage(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BackFrontMessage> reader = _BackFrontMessageReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  BackFrontPayloadTypeId? get payloadType => BackFrontPayloadTypeId._createOrNull(const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 4));
  dynamic get payload {
    switch (payloadType?.value) {
      case 1: return SimpleCommand.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 2: return view_structure.View.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 3: return GetToken.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 4: return dashboard_structure.Dashboard.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 5: return WakeUpMessage.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 6: return DisplayInfo.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 7: return SystemInfo.reader.vTableGetNullable(_bc, _bcOffset, 6);
      default: return null;
    }
  }

  @override
  String toString() {
    return 'BackFrontMessage{payloadType: ${payloadType}, payload: ${payload}}';
  }
}

class _BackFrontMessageReader extends fb.TableReader<BackFrontMessage> {
  const _BackFrontMessageReader();

  @override
  BackFrontMessage createObject(fb.BufferContext bc, int offset) => 
    BackFrontMessage._(bc, offset);
}

class BackFrontMessageBuilder {
  BackFrontMessageBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addPayloadType(BackFrontPayloadTypeId? payloadType) {
    fbBuilder.addUint8(0, payloadType?.value);
    return fbBuilder.offset;
  }
  int addPayloadOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BackFrontMessageObjectBuilder extends fb.ObjectBuilder {
  final BackFrontPayloadTypeId? _payloadType;
  final dynamic _payload;

  BackFrontMessageObjectBuilder({
    BackFrontPayloadTypeId? payloadType,
    dynamic payload,
  })
      : _payloadType = payloadType,
        _payload = payload;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? payloadOffset = _payload?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addUint8(0, _payloadType?.value);
    fbBuilder.addOffset(1, payloadOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
