namespace dashboardStructure;

enum DashboardItemType: byte {
  Boolean = 0,
  Numeric = 1,
  String = 2
}

table ThresholdConfig {
  id: ulong;
  trigger_value: float;
  icon_code_point: uint;
  color_value: uint;
}

table DashboardItem {
    id: ulong;
    entity_id: string;
    display_name: string;
    x_pos: float;
    y_pos: float;
    width: float;
    height: float;
    type: DashboardItemType;
    standard_icon_code_point: uint;
    standard_color_value: uint;
    unit_override: string;
    thresholds: [ThresholdConfig];
}

table DashboardData {
    items: [DashboardItem];
    background_image_id: ulong;
    background_image_path: string;
    width: float;
    height: float;
}

table Dashboard {
    app_id: ulong;
    backend_id: ulong;
    name: string;
    dashboard_data: [ubyte];
    timestamp: ulong;
}

table Update {
    backend_id: ulong;
}

table DashboardInfo {
    name: string (required);
    backend_id: ulong;
    timestamp: ulong;
}

table AllDashboardInfo {
    infos: [DashboardInfo];
}

table DashboardSaved {
    id: ulong;
    backend_id: ulong;
}
