// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library dashboard_structure;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;



enum DashboardItemType {
  Boolean(0),
  Numeric(1),
  String(2);

  final int value;
  const DashboardItemType(this.value);

  factory DashboardItemType.fromValue(int value) {
    switch (value) {
      case 0: return DashboardItemType.Boolean;
      case 1: return DashboardItemType.Numeric;
      case 2: return DashboardItemType.String;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static DashboardItemType? _createOrNull(int? value) =>
      value == null ? null : DashboardItemType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static const fb.Reader<DashboardItemType> reader = _DashboardItemTypeReader();
}

class _DashboardItemTypeReader extends fb.Reader<DashboardItemType> {
  const _DashboardItemTypeReader();

  @override
  int get size => 1;

  @override
  DashboardItemType read(fb.BufferContext bc, int offset) =>
      DashboardItemType.fromValue(const fb.Int8Reader().read(bc, offset));
}

class ThresholdConfig {
  ThresholdConfig._(this._bc, this._bcOffset);
  factory ThresholdConfig(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ThresholdConfig> reader = _ThresholdConfigReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  double get triggerValue => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 6, 0.0);
  int get iconCodePoint => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 8, 0);
  int get colorValue => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);

  @override
  String toString() {
    return 'ThresholdConfig{id: ${id}, triggerValue: ${triggerValue}, iconCodePoint: ${iconCodePoint}, colorValue: ${colorValue}}';
  }
}

class _ThresholdConfigReader extends fb.TableReader<ThresholdConfig> {
  const _ThresholdConfigReader();

  @override
  ThresholdConfig createObject(fb.BufferContext bc, int offset) => 
    ThresholdConfig._(bc, offset);
}

class ThresholdConfigBuilder {
  ThresholdConfigBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addId(int? id) {
    fbBuilder.addUint64(0, id);
    return fbBuilder.offset;
  }
  int addTriggerValue(double? triggerValue) {
    fbBuilder.addFloat32(1, triggerValue);
    return fbBuilder.offset;
  }
  int addIconCodePoint(int? iconCodePoint) {
    fbBuilder.addUint32(2, iconCodePoint);
    return fbBuilder.offset;
  }
  int addColorValue(int? colorValue) {
    fbBuilder.addUint32(3, colorValue);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ThresholdConfigObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final double? _triggerValue;
  final int? _iconCodePoint;
  final int? _colorValue;

  ThresholdConfigObjectBuilder({
    int? id,
    double? triggerValue,
    int? iconCodePoint,
    int? colorValue,
  })
      : _id = id,
        _triggerValue = triggerValue,
        _iconCodePoint = iconCodePoint,
        _colorValue = colorValue;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(4);
    fbBuilder.addUint64(0, _id);
    fbBuilder.addFloat32(1, _triggerValue);
    fbBuilder.addUint32(2, _iconCodePoint);
    fbBuilder.addUint32(3, _colorValue);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class DashboardItem {
  DashboardItem._(this._bc, this._bcOffset);
  factory DashboardItem(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DashboardItem> reader = _DashboardItemReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get entityId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get displayName => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  double get xPos => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 10, 0.0);
  double get yPos => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 12, 0.0);
  double get width => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 14, 0.0);
  double get height => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 16, 0.0);
  DashboardItemType get type => DashboardItemType.fromValue(const fb.Int8Reader().vTableGet(_bc, _bcOffset, 18, 0));
  int get standardIconCodePoint => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 20, 0);
  int get standardColorValue => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 22, 0);
  String? get unitOverride => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 24);
  List<ThresholdConfig>? get thresholds => const fb.ListReader<ThresholdConfig>(ThresholdConfig.reader).vTableGetNullable(_bc, _bcOffset, 26);

  @override
  String toString() {
    return 'DashboardItem{id: ${id}, entityId: ${entityId}, displayName: ${displayName}, xPos: ${xPos}, yPos: ${yPos}, width: ${width}, height: ${height}, type: ${type}, standardIconCodePoint: ${standardIconCodePoint}, standardColorValue: ${standardColorValue}, unitOverride: ${unitOverride}, thresholds: ${thresholds}}';
  }
}

class _DashboardItemReader extends fb.TableReader<DashboardItem> {
  const _DashboardItemReader();

  @override
  DashboardItem createObject(fb.BufferContext bc, int offset) => 
    DashboardItem._(bc, offset);
}

class DashboardItemBuilder {
  DashboardItemBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(12);
  }

  int addId(int? id) {
    fbBuilder.addUint64(0, id);
    return fbBuilder.offset;
  }
  int addEntityIdOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addDisplayNameOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addXPos(double? xPos) {
    fbBuilder.addFloat32(3, xPos);
    return fbBuilder.offset;
  }
  int addYPos(double? yPos) {
    fbBuilder.addFloat32(4, yPos);
    return fbBuilder.offset;
  }
  int addWidth(double? width) {
    fbBuilder.addFloat32(5, width);
    return fbBuilder.offset;
  }
  int addHeight(double? height) {
    fbBuilder.addFloat32(6, height);
    return fbBuilder.offset;
  }
  int addType(DashboardItemType? type) {
    fbBuilder.addInt8(7, type?.value);
    return fbBuilder.offset;
  }
  int addStandardIconCodePoint(int? standardIconCodePoint) {
    fbBuilder.addUint32(8, standardIconCodePoint);
    return fbBuilder.offset;
  }
  int addStandardColorValue(int? standardColorValue) {
    fbBuilder.addUint32(9, standardColorValue);
    return fbBuilder.offset;
  }
  int addUnitOverrideOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }
  int addThresholdsOffset(int? offset) {
    fbBuilder.addOffset(11, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DashboardItemObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final String? _entityId;
  final String? _displayName;
  final double? _xPos;
  final double? _yPos;
  final double? _width;
  final double? _height;
  final DashboardItemType? _type;
  final int? _standardIconCodePoint;
  final int? _standardColorValue;
  final String? _unitOverride;
  final List<ThresholdConfigObjectBuilder>? _thresholds;

  DashboardItemObjectBuilder({
    int? id,
    String? entityId,
    String? displayName,
    double? xPos,
    double? yPos,
    double? width,
    double? height,
    DashboardItemType? type,
    int? standardIconCodePoint,
    int? standardColorValue,
    String? unitOverride,
    List<ThresholdConfigObjectBuilder>? thresholds,
  })
      : _id = id,
        _entityId = entityId,
        _displayName = displayName,
        _xPos = xPos,
        _yPos = yPos,
        _width = width,
        _height = height,
        _type = type,
        _standardIconCodePoint = standardIconCodePoint,
        _standardColorValue = standardColorValue,
        _unitOverride = unitOverride,
        _thresholds = thresholds;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? entityIdOffset = _entityId == null ? null
        : fbBuilder.writeString(_entityId!);
    final int? displayNameOffset = _displayName == null ? null
        : fbBuilder.writeString(_displayName!);
    final int? unitOverrideOffset = _unitOverride == null ? null
        : fbBuilder.writeString(_unitOverride!);
    final int? thresholdsOffset = _thresholds == null ? null
        : fbBuilder.writeList(_thresholds!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(12);
    fbBuilder.addUint64(0, _id);
    fbBuilder.addOffset(1, entityIdOffset);
    fbBuilder.addOffset(2, displayNameOffset);
    fbBuilder.addFloat32(3, _xPos);
    fbBuilder.addFloat32(4, _yPos);
    fbBuilder.addFloat32(5, _width);
    fbBuilder.addFloat32(6, _height);
    fbBuilder.addInt8(7, _type?.value);
    fbBuilder.addUint32(8, _standardIconCodePoint);
    fbBuilder.addUint32(9, _standardColorValue);
    fbBuilder.addOffset(10, unitOverrideOffset);
    fbBuilder.addOffset(11, thresholdsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class DashboardData {
  DashboardData._(this._bc, this._bcOffset);
  factory DashboardData(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DashboardData> reader = _DashboardDataReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<DashboardItem>? get items => const fb.ListReader<DashboardItem>(DashboardItem.reader).vTableGetNullable(_bc, _bcOffset, 4);
  int get backgroundImageId => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);
  String? get backgroundImagePath => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  double get width => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 10, 0.0);
  double get height => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 12, 0.0);

  @override
  String toString() {
    return 'DashboardData{items: ${items}, backgroundImageId: ${backgroundImageId}, backgroundImagePath: ${backgroundImagePath}, width: ${width}, height: ${height}}';
  }
}

class _DashboardDataReader extends fb.TableReader<DashboardData> {
  const _DashboardDataReader();

  @override
  DashboardData createObject(fb.BufferContext bc, int offset) => 
    DashboardData._(bc, offset);
}

class DashboardDataBuilder {
  DashboardDataBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(5);
  }

  int addItemsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addBackgroundImageId(int? backgroundImageId) {
    fbBuilder.addUint64(1, backgroundImageId);
    return fbBuilder.offset;
  }
  int addBackgroundImagePathOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addWidth(double? width) {
    fbBuilder.addFloat32(3, width);
    return fbBuilder.offset;
  }
  int addHeight(double? height) {
    fbBuilder.addFloat32(4, height);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DashboardDataObjectBuilder extends fb.ObjectBuilder {
  final List<DashboardItemObjectBuilder>? _items;
  final int? _backgroundImageId;
  final String? _backgroundImagePath;
  final double? _width;
  final double? _height;

  DashboardDataObjectBuilder({
    List<DashboardItemObjectBuilder>? items,
    int? backgroundImageId,
    String? backgroundImagePath,
    double? width,
    double? height,
  })
      : _items = items,
        _backgroundImageId = backgroundImageId,
        _backgroundImagePath = backgroundImagePath,
        _width = width,
        _height = height;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? itemsOffset = _items == null ? null
        : fbBuilder.writeList(_items!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? backgroundImagePathOffset = _backgroundImagePath == null ? null
        : fbBuilder.writeString(_backgroundImagePath!);
    fbBuilder.startTable(5);
    fbBuilder.addOffset(0, itemsOffset);
    fbBuilder.addUint64(1, _backgroundImageId);
    fbBuilder.addOffset(2, backgroundImagePathOffset);
    fbBuilder.addFloat32(3, _width);
    fbBuilder.addFloat32(4, _height);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Dashboard {
  Dashboard._(this._bc, this._bcOffset);
  factory Dashboard(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Dashboard> reader = _DashboardReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get appId => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get backendId => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  List<int>? get dashboardData => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 10);
  int get timestamp => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 12, 0);

  @override
  String toString() {
    return 'Dashboard{appId: ${appId}, backendId: ${backendId}, name: ${name}, dashboardData: ${dashboardData}, timestamp: ${timestamp}}';
  }
}

class _DashboardReader extends fb.TableReader<Dashboard> {
  const _DashboardReader();

  @override
  Dashboard createObject(fb.BufferContext bc, int offset) => 
    Dashboard._(bc, offset);
}

class DashboardBuilder {
  DashboardBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(5);
  }

  int addAppId(int? appId) {
    fbBuilder.addUint64(0, appId);
    return fbBuilder.offset;
  }
  int addBackendId(int? backendId) {
    fbBuilder.addUint64(1, backendId);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addDashboardDataOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addTimestamp(int? timestamp) {
    fbBuilder.addUint64(4, timestamp);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DashboardObjectBuilder extends fb.ObjectBuilder {
  final int? _appId;
  final int? _backendId;
  final String? _name;
  final List<int>? _dashboardData;
  final int? _timestamp;

  DashboardObjectBuilder({
    int? appId,
    int? backendId,
    String? name,
    List<int>? dashboardData,
    int? timestamp,
  })
      : _appId = appId,
        _backendId = backendId,
        _name = name,
        _dashboardData = dashboardData,
        _timestamp = timestamp;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    final int? dashboardDataOffset = _dashboardData == null ? null
        : fbBuilder.writeListUint8(_dashboardData!);
    fbBuilder.startTable(5);
    fbBuilder.addUint64(0, _appId);
    fbBuilder.addUint64(1, _backendId);
    fbBuilder.addOffset(2, nameOffset);
    fbBuilder.addOffset(3, dashboardDataOffset);
    fbBuilder.addUint64(4, _timestamp);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Update {
  Update._(this._bc, this._bcOffset);
  factory Update(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Update> reader = _UpdateReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get backendId => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);

  @override
  String toString() {
    return 'Update{backendId: ${backendId}}';
  }
}

class _UpdateReader extends fb.TableReader<Update> {
  const _UpdateReader();

  @override
  Update createObject(fb.BufferContext bc, int offset) => 
    Update._(bc, offset);
}

class UpdateBuilder {
  UpdateBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addBackendId(int? backendId) {
    fbBuilder.addUint64(0, backendId);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class UpdateObjectBuilder extends fb.ObjectBuilder {
  final int? _backendId;

  UpdateObjectBuilder({
    int? backendId,
  })
      : _backendId = backendId;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addUint64(0, _backendId);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class DashboardInfo {
  DashboardInfo._(this._bc, this._bcOffset);
  factory DashboardInfo(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DashboardInfo> reader = _DashboardInfoReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  int get backendId => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get timestamp => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'DashboardInfo{name: ${name}, backendId: ${backendId}, timestamp: ${timestamp}}';
  }
}

class _DashboardInfoReader extends fb.TableReader<DashboardInfo> {
  const _DashboardInfoReader();

  @override
  DashboardInfo createObject(fb.BufferContext bc, int offset) => 
    DashboardInfo._(bc, offset);
}

class DashboardInfoBuilder {
  DashboardInfoBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addBackendId(int? backendId) {
    fbBuilder.addUint64(1, backendId);
    return fbBuilder.offset;
  }
  int addTimestamp(int? timestamp) {
    fbBuilder.addUint64(2, timestamp);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DashboardInfoObjectBuilder extends fb.ObjectBuilder {
  final String? _name;
  final int? _backendId;
  final int? _timestamp;

  DashboardInfoObjectBuilder({
    String? name,
    int? backendId,
    int? timestamp,
  })
      : _name = name,
        _backendId = backendId,
        _timestamp = timestamp;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addUint64(1, _backendId);
    fbBuilder.addUint64(2, _timestamp);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class AllDashboardInfo {
  AllDashboardInfo._(this._bc, this._bcOffset);
  factory AllDashboardInfo(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<AllDashboardInfo> reader = _AllDashboardInfoReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<DashboardInfo>? get infos => const fb.ListReader<DashboardInfo>(DashboardInfo.reader).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'AllDashboardInfo{infos: ${infos}}';
  }
}

class _AllDashboardInfoReader extends fb.TableReader<AllDashboardInfo> {
  const _AllDashboardInfoReader();

  @override
  AllDashboardInfo createObject(fb.BufferContext bc, int offset) => 
    AllDashboardInfo._(bc, offset);
}

class AllDashboardInfoBuilder {
  AllDashboardInfoBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addInfosOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class AllDashboardInfoObjectBuilder extends fb.ObjectBuilder {
  final List<DashboardInfoObjectBuilder>? _infos;

  AllDashboardInfoObjectBuilder({
    List<DashboardInfoObjectBuilder>? infos,
  })
      : _infos = infos;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? infosOffset = _infos == null ? null
        : fbBuilder.writeList(_infos!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, infosOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class DashboardSaved {
  DashboardSaved._(this._bc, this._bcOffset);
  factory DashboardSaved(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DashboardSaved> reader = _DashboardSavedReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get backendId => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'DashboardSaved{id: ${id}, backendId: ${backendId}}';
  }
}

class _DashboardSavedReader extends fb.TableReader<DashboardSaved> {
  const _DashboardSavedReader();

  @override
  DashboardSaved createObject(fb.BufferContext bc, int offset) => 
    DashboardSaved._(bc, offset);
}

class DashboardSavedBuilder {
  DashboardSavedBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addId(int? id) {
    fbBuilder.addUint64(0, id);
    return fbBuilder.offset;
  }
  int addBackendId(int? backendId) {
    fbBuilder.addUint64(1, backendId);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DashboardSavedObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final int? _backendId;

  DashboardSavedObjectBuilder({
    int? id,
    int? backendId,
  })
      : _id = id,
        _backendId = backendId;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(2);
    fbBuilder.addUint64(0, _id);
    fbBuilder.addUint64(1, _backendId);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
