namespace frontBack;

enum FrontendSignal : byte { UNKNOWN, READY, STANDBY, GET_SYSTEM_INFO}
enum VerboseLevel : byte {
    TraceL3  = 0,
    TraceL2  = 1,
    TraceL1  = 2,
    Debug    = 3,
    Info     = 4,
    Notice   = 5,
    Warning  = 6,
    Error    = 7,
    Critical = 8
}

table FrontSignal { signal: FrontendSignal; }

table GetToken {
    provider: string (required);
}

table GetDashboard {
    id: ulong;
}

table LogMessage {
    level:   VerboseLevel = Debug;
    message: string (required);
}

table VersionInfo {
    version: string (required);
}

union FrontBackPayload {
    FrontSignal,
    GetToken,
    GetDashboard,
    LogMessage,
    VersionInfo
}

table FrontBackMessage {
    payload: FrontBackPayload;
}

root_type FrontBackMessage;
