// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library front_back;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;



enum FrontendSignal {
  UNKNOWN(0),
  READY(1),
  STANDBY(2),
  GET_SYSTEM_INFO(3);

  final int value;
  const FrontendSignal(this.value);

  factory FrontendSignal.fromValue(int value) {
    switch (value) {
      case 0: return FrontendSignal.UNKNOWN;
      case 1: return FrontendSignal.READY;
      case 2: return FrontendSignal.STANDBY;
      case 3: return FrontendSignal.GET_SYSTEM_INFO;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static FrontendSignal? _createOrNull(int? value) =>
      value == null ? null : FrontendSignal.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 3;
  static const fb.Reader<FrontendSignal> reader = _FrontendSignalReader();
}

class _FrontendSignalReader extends fb.Reader<FrontendSignal> {
  const _FrontendSignalReader();

  @override
  int get size => 1;

  @override
  FrontendSignal read(fb.BufferContext bc, int offset) =>
      FrontendSignal.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum VerboseLevel {
  TraceL3(0),
  TraceL2(1),
  TraceL1(2),
  Debug(3),
  Info(4),
  Notice(5),
  Warning(6),
  Error(7),
  Critical(8);

  final int value;
  const VerboseLevel(this.value);

  factory VerboseLevel.fromValue(int value) {
    switch (value) {
      case 0: return VerboseLevel.TraceL3;
      case 1: return VerboseLevel.TraceL2;
      case 2: return VerboseLevel.TraceL1;
      case 3: return VerboseLevel.Debug;
      case 4: return VerboseLevel.Info;
      case 5: return VerboseLevel.Notice;
      case 6: return VerboseLevel.Warning;
      case 7: return VerboseLevel.Error;
      case 8: return VerboseLevel.Critical;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static VerboseLevel? _createOrNull(int? value) =>
      value == null ? null : VerboseLevel.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 8;
  static const fb.Reader<VerboseLevel> reader = _VerboseLevelReader();
}

class _VerboseLevelReader extends fb.Reader<VerboseLevel> {
  const _VerboseLevelReader();

  @override
  int get size => 1;

  @override
  VerboseLevel read(fb.BufferContext bc, int offset) =>
      VerboseLevel.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum FrontBackPayloadTypeId {
  NONE(0),
  FrontSignal(1),
  GetToken(2),
  GetDashboard(3),
  LogMessage(4),
  VersionInfo(5);

  final int value;
  const FrontBackPayloadTypeId(this.value);

  factory FrontBackPayloadTypeId.fromValue(int value) {
    switch (value) {
      case 0: return FrontBackPayloadTypeId.NONE;
      case 1: return FrontBackPayloadTypeId.FrontSignal;
      case 2: return FrontBackPayloadTypeId.GetToken;
      case 3: return FrontBackPayloadTypeId.GetDashboard;
      case 4: return FrontBackPayloadTypeId.LogMessage;
      case 5: return FrontBackPayloadTypeId.VersionInfo;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static FrontBackPayloadTypeId? _createOrNull(int? value) =>
      value == null ? null : FrontBackPayloadTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 5;
  static const fb.Reader<FrontBackPayloadTypeId> reader = _FrontBackPayloadTypeIdReader();
}

class _FrontBackPayloadTypeIdReader extends fb.Reader<FrontBackPayloadTypeId> {
  const _FrontBackPayloadTypeIdReader();

  @override
  int get size => 1;

  @override
  FrontBackPayloadTypeId read(fb.BufferContext bc, int offset) =>
      FrontBackPayloadTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class FrontSignal {
  FrontSignal._(this._bc, this._bcOffset);
  factory FrontSignal(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<FrontSignal> reader = _FrontSignalReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  FrontendSignal get signal => FrontendSignal.fromValue(const fb.Int8Reader().vTableGet(_bc, _bcOffset, 4, 0));

  @override
  String toString() {
    return 'FrontSignal{signal: ${signal}}';
  }
}

class _FrontSignalReader extends fb.TableReader<FrontSignal> {
  const _FrontSignalReader();

  @override
  FrontSignal createObject(fb.BufferContext bc, int offset) => 
    FrontSignal._(bc, offset);
}

class FrontSignalBuilder {
  FrontSignalBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addSignal(FrontendSignal? signal) {
    fbBuilder.addInt8(0, signal?.value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class FrontSignalObjectBuilder extends fb.ObjectBuilder {
  final FrontendSignal? _signal;

  FrontSignalObjectBuilder({
    FrontendSignal? signal,
  })
      : _signal = signal;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addInt8(0, _signal?.value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class GetToken {
  GetToken._(this._bc, this._bcOffset);
  factory GetToken(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<GetToken> reader = _GetTokenReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get provider => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'GetToken{provider: ${provider}}';
  }
}

class _GetTokenReader extends fb.TableReader<GetToken> {
  const _GetTokenReader();

  @override
  GetToken createObject(fb.BufferContext bc, int offset) => 
    GetToken._(bc, offset);
}

class GetTokenBuilder {
  GetTokenBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addProviderOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class GetTokenObjectBuilder extends fb.ObjectBuilder {
  final String? _provider;

  GetTokenObjectBuilder({
    String? provider,
  })
      : _provider = provider;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? providerOffset = _provider == null ? null
        : fbBuilder.writeString(_provider!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, providerOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class GetDashboard {
  GetDashboard._(this._bc, this._bcOffset);
  factory GetDashboard(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<GetDashboard> reader = _GetDashboardReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);

  @override
  String toString() {
    return 'GetDashboard{id: ${id}}';
  }
}

class _GetDashboardReader extends fb.TableReader<GetDashboard> {
  const _GetDashboardReader();

  @override
  GetDashboard createObject(fb.BufferContext bc, int offset) => 
    GetDashboard._(bc, offset);
}

class GetDashboardBuilder {
  GetDashboardBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addId(int? id) {
    fbBuilder.addUint64(0, id);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class GetDashboardObjectBuilder extends fb.ObjectBuilder {
  final int? _id;

  GetDashboardObjectBuilder({
    int? id,
  })
      : _id = id;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addUint64(0, _id);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class LogMessage {
  LogMessage._(this._bc, this._bcOffset);
  factory LogMessage(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<LogMessage> reader = _LogMessageReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  VerboseLevel get level => VerboseLevel.fromValue(const fb.Int8Reader().vTableGet(_bc, _bcOffset, 4, 3));
  String? get message => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'LogMessage{level: ${level}, message: ${message}}';
  }
}

class _LogMessageReader extends fb.TableReader<LogMessage> {
  const _LogMessageReader();

  @override
  LogMessage createObject(fb.BufferContext bc, int offset) => 
    LogMessage._(bc, offset);
}

class LogMessageBuilder {
  LogMessageBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addLevel(VerboseLevel? level) {
    fbBuilder.addInt8(0, level?.value);
    return fbBuilder.offset;
  }
  int addMessageOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class LogMessageObjectBuilder extends fb.ObjectBuilder {
  final VerboseLevel? _level;
  final String? _message;

  LogMessageObjectBuilder({
    VerboseLevel? level,
    String? message,
  })
      : _level = level,
        _message = message;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? messageOffset = _message == null ? null
        : fbBuilder.writeString(_message!);
    fbBuilder.startTable(2);
    fbBuilder.addInt8(0, _level?.value);
    fbBuilder.addOffset(1, messageOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class VersionInfo {
  VersionInfo._(this._bc, this._bcOffset);
  factory VersionInfo(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VersionInfo> reader = _VersionInfoReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get version => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'VersionInfo{version: ${version}}';
  }
}

class _VersionInfoReader extends fb.TableReader<VersionInfo> {
  const _VersionInfoReader();

  @override
  VersionInfo createObject(fb.BufferContext bc, int offset) => 
    VersionInfo._(bc, offset);
}

class VersionInfoBuilder {
  VersionInfoBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addVersionOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VersionInfoObjectBuilder extends fb.ObjectBuilder {
  final String? _version;

  VersionInfoObjectBuilder({
    String? version,
  })
      : _version = version;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? versionOffset = _version == null ? null
        : fbBuilder.writeString(_version!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, versionOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class FrontBackMessage {
  FrontBackMessage._(this._bc, this._bcOffset);
  factory FrontBackMessage(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<FrontBackMessage> reader = _FrontBackMessageReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  FrontBackPayloadTypeId? get payloadType => FrontBackPayloadTypeId._createOrNull(const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 4));
  dynamic get payload {
    switch (payloadType?.value) {
      case 1: return FrontSignal.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 2: return GetToken.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 3: return GetDashboard.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 4: return LogMessage.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 5: return VersionInfo.reader.vTableGetNullable(_bc, _bcOffset, 6);
      default: return null;
    }
  }

  @override
  String toString() {
    return 'FrontBackMessage{payloadType: ${payloadType}, payload: ${payload}}';
  }
}

class _FrontBackMessageReader extends fb.TableReader<FrontBackMessage> {
  const _FrontBackMessageReader();

  @override
  FrontBackMessage createObject(fb.BufferContext bc, int offset) => 
    FrontBackMessage._(bc, offset);
}

class FrontBackMessageBuilder {
  FrontBackMessageBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addPayloadType(FrontBackPayloadTypeId? payloadType) {
    fbBuilder.addUint8(0, payloadType?.value);
    return fbBuilder.offset;
  }
  int addPayloadOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class FrontBackMessageObjectBuilder extends fb.ObjectBuilder {
  final FrontBackPayloadTypeId? _payloadType;
  final dynamic _payload;

  FrontBackMessageObjectBuilder({
    FrontBackPayloadTypeId? payloadType,
    dynamic payload,
  })
      : _payloadType = payloadType,
        _payload = payload;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? payloadOffset = _payload?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addUint8(0, _payloadType?.value);
    fbBuilder.addOffset(1, payloadOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
