// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library view_structure;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;



enum WidgetPropertyType {
  None(0),
  String(1),
  Int(2),
  Float(3),
  Bool(4),
  RawBytes(5);

  final int value;
  const WidgetPropertyType(this.value);

  factory WidgetPropertyType.fromValue(int value) {
    switch (value) {
      case 0: return WidgetPropertyType.None;
      case 1: return WidgetPropertyType.String;
      case 2: return WidgetPropertyType.Int;
      case 3: return WidgetPropertyType.Float;
      case 4: return WidgetPropertyType.Bool;
      case 5: return WidgetPropertyType.RawBytes;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static WidgetPropertyType? _createOrNull(int? value) =>
      value == null ? null : WidgetPropertyType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 5;
  static const fb.Reader<WidgetPropertyType> reader = _WidgetPropertyTypeReader();
}

class _WidgetPropertyTypeReader extends fb.Reader<WidgetPropertyType> {
  const _WidgetPropertyTypeReader();

  @override
  int get size => 1;

  @override
  WidgetPropertyType read(fb.BufferContext bc, int offset) =>
      WidgetPropertyType.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum WidgetPropertyValueTypeId {
  NONE(0),
  StringValue(1),
  IntValue(2),
  FloatValue(3),
  BoolValue(4),
  RawBytes(5);

  final int value;
  const WidgetPropertyValueTypeId(this.value);

  factory WidgetPropertyValueTypeId.fromValue(int value) {
    switch (value) {
      case 0: return WidgetPropertyValueTypeId.NONE;
      case 1: return WidgetPropertyValueTypeId.StringValue;
      case 2: return WidgetPropertyValueTypeId.IntValue;
      case 3: return WidgetPropertyValueTypeId.FloatValue;
      case 4: return WidgetPropertyValueTypeId.BoolValue;
      case 5: return WidgetPropertyValueTypeId.RawBytes;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static WidgetPropertyValueTypeId? _createOrNull(int? value) =>
      value == null ? null : WidgetPropertyValueTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 5;
  static const fb.Reader<WidgetPropertyValueTypeId> reader = _WidgetPropertyValueTypeIdReader();
}

class _WidgetPropertyValueTypeIdReader extends fb.Reader<WidgetPropertyValueTypeId> {
  const _WidgetPropertyValueTypeIdReader();

  @override
  int get size => 1;

  @override
  WidgetPropertyValueTypeId read(fb.BufferContext bc, int offset) =>
      WidgetPropertyValueTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class StringValue {
  StringValue._(this._bc, this._bcOffset);
  factory StringValue(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StringValue> reader = _StringValueReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get value => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'StringValue{value: ${value}}';
  }
}

class _StringValueReader extends fb.TableReader<StringValue> {
  const _StringValueReader();

  @override
  StringValue createObject(fb.BufferContext bc, int offset) => 
    StringValue._(bc, offset);
}

class StringValueBuilder {
  StringValueBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addValueOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StringValueObjectBuilder extends fb.ObjectBuilder {
  final String? _value;

  StringValueObjectBuilder({
    String? value,
  })
      : _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? valueOffset = _value == null ? null
        : fbBuilder.writeString(_value!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, valueOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class IntValue {
  IntValue._(this._bc, this._bcOffset);
  factory IntValue(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<IntValue> reader = _IntValueReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get value => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 4, 0);

  @override
  String toString() {
    return 'IntValue{value: ${value}}';
  }
}

class _IntValueReader extends fb.TableReader<IntValue> {
  const _IntValueReader();

  @override
  IntValue createObject(fb.BufferContext bc, int offset) => 
    IntValue._(bc, offset);
}

class IntValueBuilder {
  IntValueBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addValue(int? value) {
    fbBuilder.addInt32(0, value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class IntValueObjectBuilder extends fb.ObjectBuilder {
  final int? _value;

  IntValueObjectBuilder({
    int? value,
  })
      : _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addInt32(0, _value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class FloatValue {
  FloatValue._(this._bc, this._bcOffset);
  factory FloatValue(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<FloatValue> reader = _FloatValueReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get value => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 4, 0.0);

  @override
  String toString() {
    return 'FloatValue{value: ${value}}';
  }
}

class _FloatValueReader extends fb.TableReader<FloatValue> {
  const _FloatValueReader();

  @override
  FloatValue createObject(fb.BufferContext bc, int offset) => 
    FloatValue._(bc, offset);
}

class FloatValueBuilder {
  FloatValueBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addValue(double? value) {
    fbBuilder.addFloat32(0, value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class FloatValueObjectBuilder extends fb.ObjectBuilder {
  final double? _value;

  FloatValueObjectBuilder({
    double? value,
  })
      : _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addFloat32(0, _value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BoolValue {
  BoolValue._(this._bc, this._bcOffset);
  factory BoolValue(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BoolValue> reader = _BoolValueReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  bool get value => const fb.BoolReader().vTableGet(_bc, _bcOffset, 4, false);

  @override
  String toString() {
    return 'BoolValue{value: ${value}}';
  }
}

class _BoolValueReader extends fb.TableReader<BoolValue> {
  const _BoolValueReader();

  @override
  BoolValue createObject(fb.BufferContext bc, int offset) => 
    BoolValue._(bc, offset);
}

class BoolValueBuilder {
  BoolValueBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addValue(bool? value) {
    fbBuilder.addBool(0, value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BoolValueObjectBuilder extends fb.ObjectBuilder {
  final bool? _value;

  BoolValueObjectBuilder({
    bool? value,
  })
      : _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addBool(0, _value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class RawBytes {
  RawBytes._(this._bc, this._bcOffset);
  factory RawBytes(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<RawBytes> reader = _RawBytesReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int>? get data => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'RawBytes{data: ${data}}';
  }
}

class _RawBytesReader extends fb.TableReader<RawBytes> {
  const _RawBytesReader();

  @override
  RawBytes createObject(fb.BufferContext bc, int offset) => 
    RawBytes._(bc, offset);
}

class RawBytesBuilder {
  RawBytesBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addDataOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class RawBytesObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _data;

  RawBytesObjectBuilder({
    List<int>? data,
  })
      : _data = data;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dataOffset = _data == null ? null
        : fbBuilder.writeListUint8(_data!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, dataOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class WidgetProperty {
  WidgetProperty._(this._bc, this._bcOffset);
  factory WidgetProperty(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<WidgetProperty> reader = _WidgetPropertyReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get keyId => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  WidgetPropertyType get type => WidgetPropertyType.fromValue(const fb.Int8Reader().vTableGet(_bc, _bcOffset, 6, 0));
  WidgetPropertyValueTypeId? get valueType => WidgetPropertyValueTypeId._createOrNull(const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 8));
  dynamic get value {
    switch (valueType?.value) {
      case 1: return StringValue.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 2: return IntValue.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 3: return FloatValue.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 4: return BoolValue.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 5: return RawBytes.reader.vTableGetNullable(_bc, _bcOffset, 10);
      default: return null;
    }
  }

  @override
  String toString() {
    return 'WidgetProperty{keyId: ${keyId}, type: ${type}, valueType: ${valueType}, value: ${value}}';
  }
}

class _WidgetPropertyReader extends fb.TableReader<WidgetProperty> {
  const _WidgetPropertyReader();

  @override
  WidgetProperty createObject(fb.BufferContext bc, int offset) => 
    WidgetProperty._(bc, offset);
}

class WidgetPropertyBuilder {
  WidgetPropertyBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addKeyId(int? keyId) {
    fbBuilder.addInt32(0, keyId);
    return fbBuilder.offset;
  }
  int addType(WidgetPropertyType? type) {
    fbBuilder.addInt8(1, type?.value);
    return fbBuilder.offset;
  }
  int addValueType(WidgetPropertyValueTypeId? valueType) {
    fbBuilder.addUint8(2, valueType?.value);
    return fbBuilder.offset;
  }
  int addValueOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class WidgetPropertyObjectBuilder extends fb.ObjectBuilder {
  final int? _keyId;
  final WidgetPropertyType? _type;
  final WidgetPropertyValueTypeId? _valueType;
  final dynamic _value;

  WidgetPropertyObjectBuilder({
    int? keyId,
    WidgetPropertyType? type,
    WidgetPropertyValueTypeId? valueType,
    dynamic value,
  })
      : _keyId = keyId,
        _type = type,
        _valueType = valueType,
        _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? valueOffset = _value?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(4);
    fbBuilder.addInt32(0, _keyId);
    fbBuilder.addInt8(1, _type?.value);
    fbBuilder.addUint8(2, _valueType?.value);
    fbBuilder.addOffset(3, valueOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Widget {
  Widget._(this._bc, this._bcOffset);
  factory Widget(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Widget> reader = _WidgetReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get widgetId => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 6, 0);
  double get xPos => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 8, 0.0);
  double get yPos => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 10, 0.0);
  double get width => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 12, 0.0);
  double get height => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 14, 0.0);
  List<WidgetProperty>? get properties => const fb.ListReader<WidgetProperty>(WidgetProperty.reader).vTableGetNullable(_bc, _bcOffset, 16);

  @override
  String toString() {
    return 'Widget{id: ${id}, widgetId: ${widgetId}, xPos: ${xPos}, yPos: ${yPos}, width: ${width}, height: ${height}, properties: ${properties}}';
  }
}

class _WidgetReader extends fb.TableReader<Widget> {
  const _WidgetReader();

  @override
  Widget createObject(fb.BufferContext bc, int offset) => 
    Widget._(bc, offset);
}

class WidgetBuilder {
  WidgetBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(7);
  }

  int addId(int? id) {
    fbBuilder.addUint64(0, id);
    return fbBuilder.offset;
  }
  int addWidgetId(int? widgetId) {
    fbBuilder.addInt32(1, widgetId);
    return fbBuilder.offset;
  }
  int addXPos(double? xPos) {
    fbBuilder.addFloat32(2, xPos);
    return fbBuilder.offset;
  }
  int addYPos(double? yPos) {
    fbBuilder.addFloat32(3, yPos);
    return fbBuilder.offset;
  }
  int addWidth(double? width) {
    fbBuilder.addFloat32(4, width);
    return fbBuilder.offset;
  }
  int addHeight(double? height) {
    fbBuilder.addFloat32(5, height);
    return fbBuilder.offset;
  }
  int addPropertiesOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class WidgetObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final int? _widgetId;
  final double? _xPos;
  final double? _yPos;
  final double? _width;
  final double? _height;
  final List<WidgetPropertyObjectBuilder>? _properties;

  WidgetObjectBuilder({
    int? id,
    int? widgetId,
    double? xPos,
    double? yPos,
    double? width,
    double? height,
    List<WidgetPropertyObjectBuilder>? properties,
  })
      : _id = id,
        _widgetId = widgetId,
        _xPos = xPos,
        _yPos = yPos,
        _width = width,
        _height = height,
        _properties = properties;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? propertiesOffset = _properties == null ? null
        : fbBuilder.writeList(_properties!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(7);
    fbBuilder.addUint64(0, _id);
    fbBuilder.addInt32(1, _widgetId);
    fbBuilder.addFloat32(2, _xPos);
    fbBuilder.addFloat32(3, _yPos);
    fbBuilder.addFloat32(4, _width);
    fbBuilder.addFloat32(5, _height);
    fbBuilder.addOffset(6, propertiesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Page {
  Page._(this._bc, this._bcOffset);
  factory Page(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Page> reader = _PageReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get number => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 6, 0);
  List<Widget>? get widgets => const fb.ListReader<Widget>(Widget.reader).vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'Page{id: ${id}, number: ${number}, widgets: ${widgets}}';
  }
}

class _PageReader extends fb.TableReader<Page> {
  const _PageReader();

  @override
  Page createObject(fb.BufferContext bc, int offset) => 
    Page._(bc, offset);
}

class PageBuilder {
  PageBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addId(int? id) {
    fbBuilder.addUint64(0, id);
    return fbBuilder.offset;
  }
  int addNumber(int? number) {
    fbBuilder.addInt32(1, number);
    return fbBuilder.offset;
  }
  int addWidgetsOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PageObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final int? _number;
  final List<WidgetObjectBuilder>? _widgets;

  PageObjectBuilder({
    int? id,
    int? number,
    List<WidgetObjectBuilder>? widgets,
  })
      : _id = id,
        _number = number,
        _widgets = widgets;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? widgetsOffset = _widgets == null ? null
        : fbBuilder.writeList(_widgets!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(3);
    fbBuilder.addUint64(0, _id);
    fbBuilder.addInt32(1, _number);
    fbBuilder.addOffset(2, widgetsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class View {
  View._(this._bc, this._bcOffset);
  factory View(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<View> reader = _ViewReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get language => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  int get timestamp => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get theme => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 8, 0);
  List<int>? get data => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 10);

  @override
  String toString() {
    return 'View{language: ${language}, timestamp: ${timestamp}, theme: ${theme}, data: ${data}}';
  }
}

class _ViewReader extends fb.TableReader<View> {
  const _ViewReader();

  @override
  View createObject(fb.BufferContext bc, int offset) => 
    View._(bc, offset);
}

class ViewBuilder {
  ViewBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addLanguageOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addTimestamp(int? timestamp) {
    fbBuilder.addUint64(1, timestamp);
    return fbBuilder.offset;
  }
  int addTheme(int? theme) {
    fbBuilder.addInt32(2, theme);
    return fbBuilder.offset;
  }
  int addDataOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ViewObjectBuilder extends fb.ObjectBuilder {
  final String? _language;
  final int? _timestamp;
  final int? _theme;
  final List<int>? _data;

  ViewObjectBuilder({
    String? language,
    int? timestamp,
    int? theme,
    List<int>? data,
  })
      : _language = language,
        _timestamp = timestamp,
        _theme = theme,
        _data = data;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? languageOffset = _language == null ? null
        : fbBuilder.writeString(_language!);
    final int? dataOffset = _data == null ? null
        : fbBuilder.writeListUint8(_data!);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, languageOffset);
    fbBuilder.addUint64(1, _timestamp);
    fbBuilder.addInt32(2, _theme);
    fbBuilder.addOffset(3, dataOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
