namespace viewStructure;

enum WidgetPropertyType: byte {
  None,
  String,
  Int,
  Float,
  Bool,
  RawBytes
}

union WidgetPropertyValue {
  StringValue,
  IntValue,
  FloatValue,
  BoolValue,
  RawBytes
}

table StringValue { value: string; }
table IntValue { value: int; }
table FloatValue { value: float; }
table BoolValue { value: bool; }
table RawBytes { data: [ubyte]; }

table WidgetProperty {
  key_id: int;
  type: WidgetPropertyType;
  value: WidgetPropertyValue;
}

table Widget {
  id: ulong;
  widget_id: int;
  x_pos: float;
  y_pos: float;
  width: float;
  height: float;
  properties: [WidgetProperty];
}

table Page {
  id: ulong;
  number: int;
  widgets: [Widget];
}

table View {
  language: string;
  timestamp: ulong;
  theme: int;
  data: [ubyte];
}
