// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library widget_internals;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;



class DashboardList {
  DashboardList._(this._bc, this._bcOffset);
  factory DashboardList(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DashboardList> reader = _DashboardListReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int>? get ids => const fb.ListReader<int>(fb.Uint64Reader()).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'DashboardList{ids: ${ids}}';
  }
}

class _DashboardListReader extends fb.TableReader<DashboardList> {
  const _DashboardListReader();

  @override
  DashboardList createObject(fb.BufferContext bc, int offset) => 
    DashboardList._(bc, offset);
}

class DashboardListBuilder {
  DashboardListBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addIdsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DashboardListObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _ids;

  DashboardListObjectBuilder({
    List<int>? ids,
  })
      : _ids = ids;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? idsOffset = _ids == null ? null
        : fbBuilder.writeListUint64(_ids!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, idsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BusDeparture {
  BusDeparture._(this._bc, this._bcOffset);
  factory BusDeparture(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BusDeparture> reader = _BusDepartureReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get hour => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get minute => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'BusDeparture{hour: ${hour}, minute: ${minute}}';
  }
}

class _BusDepartureReader extends fb.TableReader<BusDeparture> {
  const _BusDepartureReader();

  @override
  BusDeparture createObject(fb.BufferContext bc, int offset) => 
    BusDeparture._(bc, offset);
}

class BusDepartureBuilder {
  BusDepartureBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addHour(int? hour) {
    fbBuilder.addUint8(0, hour);
    return fbBuilder.offset;
  }
  int addMinute(int? minute) {
    fbBuilder.addUint8(1, minute);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BusDepartureObjectBuilder extends fb.ObjectBuilder {
  final int? _hour;
  final int? _minute;

  BusDepartureObjectBuilder({
    int? hour,
    int? minute,
  })
      : _hour = hour,
        _minute = minute;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(2);
    fbBuilder.addUint8(0, _hour);
    fbBuilder.addUint8(1, _minute);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BusLine {
  BusLine._(this._bc, this._bcOffset);
  factory BusLine(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BusLine> reader = _BusLineReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get number => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  List<BusDeparture>? get monFri => const fb.ListReader<BusDeparture>(BusDeparture.reader).vTableGetNullable(_bc, _bcOffset, 6);
  List<BusDeparture>? get sat => const fb.ListReader<BusDeparture>(BusDeparture.reader).vTableGetNullable(_bc, _bcOffset, 8);
  List<BusDeparture>? get sun => const fb.ListReader<BusDeparture>(BusDeparture.reader).vTableGetNullable(_bc, _bcOffset, 10);

  @override
  String toString() {
    return 'BusLine{number: ${number}, monFri: ${monFri}, sat: ${sat}, sun: ${sun}}';
  }
}

class _BusLineReader extends fb.TableReader<BusLine> {
  const _BusLineReader();

  @override
  BusLine createObject(fb.BufferContext bc, int offset) => 
    BusLine._(bc, offset);
}

class BusLineBuilder {
  BusLineBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addNumberOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addMonFriOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addSatOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addSunOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BusLineObjectBuilder extends fb.ObjectBuilder {
  final String? _number;
  final List<BusDepartureObjectBuilder>? _monFri;
  final List<BusDepartureObjectBuilder>? _sat;
  final List<BusDepartureObjectBuilder>? _sun;

  BusLineObjectBuilder({
    String? number,
    List<BusDepartureObjectBuilder>? monFri,
    List<BusDepartureObjectBuilder>? sat,
    List<BusDepartureObjectBuilder>? sun,
  })
      : _number = number,
        _monFri = monFri,
        _sat = sat,
        _sun = sun;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? numberOffset = _number == null ? null
        : fbBuilder.writeString(_number!);
    final int? monFriOffset = _monFri == null ? null
        : fbBuilder.writeList(_monFri!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? satOffset = _sat == null ? null
        : fbBuilder.writeList(_sat!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? sunOffset = _sun == null ? null
        : fbBuilder.writeList(_sun!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, numberOffset);
    fbBuilder.addOffset(1, monFriOffset);
    fbBuilder.addOffset(2, satOffset);
    fbBuilder.addOffset(3, sunOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BusSchedule {
  BusSchedule._(this._bc, this._bcOffset);
  factory BusSchedule(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BusSchedule> reader = _BusScheduleReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<BusLine>? get lines => const fb.ListReader<BusLine>(BusLine.reader).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'BusSchedule{lines: ${lines}}';
  }
}

class _BusScheduleReader extends fb.TableReader<BusSchedule> {
  const _BusScheduleReader();

  @override
  BusSchedule createObject(fb.BufferContext bc, int offset) => 
    BusSchedule._(bc, offset);
}

class BusScheduleBuilder {
  BusScheduleBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addLinesOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BusScheduleObjectBuilder extends fb.ObjectBuilder {
  final List<BusLineObjectBuilder>? _lines;

  BusScheduleObjectBuilder({
    List<BusLineObjectBuilder>? lines,
  })
      : _lines = lines;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? linesOffset = _lines == null ? null
        : fbBuilder.writeList(_lines!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, linesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class GoogleCaledarIds {
  GoogleCaledarIds._(this._bc, this._bcOffset);
  factory GoogleCaledarIds(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<GoogleCaledarIds> reader = _GoogleCaledarIdsReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<String>? get ids => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'GoogleCaledarIds{ids: ${ids}}';
  }
}

class _GoogleCaledarIdsReader extends fb.TableReader<GoogleCaledarIds> {
  const _GoogleCaledarIdsReader();

  @override
  GoogleCaledarIds createObject(fb.BufferContext bc, int offset) => 
    GoogleCaledarIds._(bc, offset);
}

class GoogleCaledarIdsBuilder {
  GoogleCaledarIdsBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addIdsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class GoogleCaledarIdsObjectBuilder extends fb.ObjectBuilder {
  final List<String>? _ids;

  GoogleCaledarIdsObjectBuilder({
    List<String>? ids,
  })
      : _ids = ids;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? idsOffset = _ids == null ? null
        : fbBuilder.writeList(_ids!.map(fbBuilder.writeString).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, idsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
